sudo: true
dist: trusty
language: java
services:
- postgresql
jdk:
- oraclejdk11
before_install:
- export TZ=Brazil/East
- chmod +x mvnw
before_script:
- psql -c 'create database gestaocolaboradores;' -U postgres
deploy:
  provider: heroku
  api_key:
    - secure: 39358219-664b-4124-9cde-f59e2b1536d7
  app: gestao-colaboradores