sudo: true
dist: trusty
language: java
services:
- postgresql
jdk:
- oraclejdk11
before_install:
- export TZ=Brazil/East
- chmod +x mvnw
before_script:
- psql -c 'create database gestaocolaboradores;' -U postgres
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    - secure: e5a923f9-9baa-42dc-b6d9-cb564c58c636
  app: gestao-colaboradores