sudo: true
dist: trusty
language: java
services:
- postgresql
jdk:
- oraclejdk11
before_install:
- export TZ=Brazil/East
- chmod +x mvnw
before_script:
- psql -c 'create database gestaocolaboradores;' -U postgres
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: udkzlc0sNLjoGEQ+nIVdOwYSSQEvLiMiDzth7Wuhs/ucBlMFZlnTQkESoOmMQ2LKNtY35h+smzzzareeOZDhoPa9Bn4rpRTFmXwkiolZJ5QlnqksByI9fcFQb5qmsgtFEUr7YRi0elYQB3U1qaP4S90MIS+aEHX9k+JxAtHICo/E/BQZaEgCOjeEvNIMCYvJ9g19D570E4X0/tPIYrbKZZX1aakPvyxaggPbTAt1MrtLuOI1MYW0RJUYDhFYOBmkfPeQD+eUUGzLfRv9IAgQjmPd25CQUXCtY54mH7p0QJmOGwZb5VnsDRonSRPz8bri82feisv8Jf03eHtkEzQd43Hk5Kvm7ZeoHFKMOgUJoaJZU7Y4y6fBsdLjzmCJL2qLeh3syVfYkYqfGFcwGKLSep4AIUgXP9xM2aXaUPOUHfQE/ycXNjSZthTemCkOe39WSzeT2jpcYtes5/dMjsY3T2YJKyOeLg0+OoRzZM6VxoDN2FUGZzg7L9T5yVeUaA9DSbjQeMsE3eaC3lEws7rQoygv0C6jLicEBbTdRoC9dFb/NGuocZmaonS6YdMyRi8ceWlDPKDtYAgKi/pW0FNiQTK7tB8ePMH5SmYQFBg/XE/Nk/LGz5D/NKnLRwdOJMlGn2HgPhIfDw8CgC73KQ6xBERPU9YNU0opL2o1ZyJjrc0=
  app: gestao-colaboradores
  on:
    repo: als-v/GestaoColaboradores
addons:
  sonarcloud:
    organization: "gestaocolaboradores"
  token:
    secure: "IlHdaHMSpphnnmHau82mxY2H4ItaYfM+xj1lTfcwjWjQ1xE+KY7XrlocijzAkjiidkdo9h4VNWnnj1qfcnX9Tt9Mk8PxrcmgLMWKUwUac9YaYKhw4+cJD5Y/KrNJa8exK4gWALTblmJFkunt8mM7zeTEJPtVNYg1ptYyL+ZyC4AKQgfqb7LhUTosm4yK6ihD5xYRSejyU3e1ULRKPtmpyB2SjhANnOU/SYUUxcnJGXxDi8IGlnkCop8tpDb0nH4b22AYHXdrDflJ4bGCMyiBo+SDPvLF6PYjfkRjmCBlmsl26ttqyR7rR1V0RdYxEq5qHOt5PPaZHfAaQKeMtRladGaNXU/cMlk4Fdyor2oociWzhMkzRf049Nyb07WWtwjfm9yQhhu5BRFZ8X2w2i9JV5WtOVvYFjc5CgeWrzXnMNkqpErRiUF3lHVpwS6wdQ5uz9C9EaqtdqIVKgKX16XJx/J+11eM9dRfGTrjsvuNnKv8bB6VnCOiO97lYPDF9q7U/9xkq8LRKxLH0s2DoGsm02ZhCs6aaT1IXD1wihqcf1ddfU4nVeqjQfOq+XBnxcRAwYAsj4A/eeamiHs08WHCwiB0ysmSF0Ck7Zw28IN6dJUWpUU9KsYFlFMiQ30yn5jWaTZn7xlRMcU3+b0LsjwUjA6TccK81bc6gRllw7e4YlU="
script:
  - mvn clean verify sonar:sonar -Pcoverage 